### ISSUE TITLE
uvicorn main:app start error in Ubuntu22

### ISSUE THREAD

**Issue by bi7jta** [bi7jta-odoo/ChatTTS#1]
uvicorn main:app --host "0.0.0.0" --port 8000
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 5, in <module>
    from uvicorn.main import main
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/__init__.py", line 2, in <module>
    from uvicorn.main import Server, main, run
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 33, in <module>
    from uvicorn.supervisors import ChangeReload, Multiprocess
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/supervisors/__init__.py", line 12, in <module>
    from uvicorn.supervisors.watchfilesreload import (
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/supervisors/watchfilesreload.py", line 7, in <module>
    from watchfiles import watch
  File "/usr/local/lib/python3.10/dist-packages/watchfiles/__init__.py", line 2, in <module>
    from .main import Change, awatch, watch
  File "/usr/local/lib/python3.10/dist-packages/watchfiles/main.py", line 9, in <module>
    import anyio
  File "/usr/local/lib/python3.10/dist-packages/anyio/__init__.py", line 27, in <module>
    from ._core._sockets import connect_tcp as connect_tcp
  File "/usr/local/lib/python3.10/dist-packages/anyio/_core/_sockets.py", line 35, in <module>
    from exceptiongroup import ExceptionGroup
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/__init__.py", line 20, in <module>
    from ._formatting import (
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 394, in <module>
    assert sys.excepthook is apport_python_hook.apport_excepthook

**Comment by bi7jta** [comment]
Fix:
```
apt install python3.10-venv
root@osboxes:/ChatTTS/ChatTTS#                  python3 -m venv myenv
root@osboxes:/ChatTTS/ChatTTS#                  source myenv/bin/activate
(myenv) root@osboxes:/ChatTTS/ChatTTS#   

pip install uvicorn fastapi watchfiles

#虚拟环境 安装依赖
pip3 install -r requirements.txt 

虚拟环境运行：

export http_proxy="http://192.168.2.156:808/"
export https_proxy="http://192.168.2.156:808/"

uvicorn main:app --host "0.0.0.0" --port 8000



第一次，需要VPS启动，下载TTS核心库：
export http_proxy="http://192.168.2.156:808/"
export https_proxy="http://192.168.2.156:808/"

export http_proxy=""
export https_proxy=""
```
